name: nnu_env
channels: 
  - conda-forge
  - defaults
dependencies:
  - pip
  - numpy
  - pandas
  - matplotlib
  - python==3.14.6
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - torch==2.13.0+cu126
      - torchaudio==2.11.0+cu126
      - torchvision==0.28.0+cu126
      - nibabel
      - nnunetv2

